namespace HMS.PatientRegistration.Infrastructure.Persistence.Seed;

/// <summary>
/// All Indian states/UTs and major cities for address cascading dropdowns.
/// </summary>
public static class IndiaGeographySeed
{
    public const string CountryCode = "IN";

    public static IReadOnlyList<(string Code, string DisplayName, string ParentCode)> States { get; } =
    [
        ("IN-AP", "Andhra Pradesh", CountryCode),
        ("IN-AR", "Arunachal Pradesh", CountryCode),
        ("IN-AS", "Assam", CountryCode),
        ("IN-BR", "Bihar", CountryCode),
        ("IN-CG", "Chhattisgarh", CountryCode),
        ("IN-GA", "Goa", CountryCode),
        ("IN-GJ", "Gujarat", CountryCode),
        ("IN-HR", "Haryana", CountryCode),
        ("IN-HP", "Himachal Pradesh", CountryCode),
        ("IN-JH", "Jharkhand", CountryCode),
        ("IN-KA", "Karnataka", CountryCode),
        ("IN-KL", "Kerala", CountryCode),
        ("IN-MP", "Madhya Pradesh", CountryCode),
        ("IN-MH", "Maharashtra", CountryCode),
        ("IN-MN", "Manipur", CountryCode),
        ("IN-ML", "Meghalaya", CountryCode),
        ("IN-MZ", "Mizoram", CountryCode),
        ("IN-NL", "Nagaland", CountryCode),
        ("IN-OR", "Odisha", CountryCode),
        ("IN-PB", "Punjab", CountryCode),
        ("IN-RJ", "Rajasthan", CountryCode),
        ("IN-SK", "Sikkim", CountryCode),
        ("IN-TN", "Tamil Nadu", CountryCode),
        ("IN-TG", "Telangana", CountryCode),
        ("IN-TR", "Tripura", CountryCode),
        ("IN-UP", "Uttar Pradesh", CountryCode),
        ("IN-UK", "Uttarakhand", CountryCode),
        ("IN-WB", "West Bengal", CountryCode),
        ("IN-AN", "Andaman and Nicobar Islands", CountryCode),
        ("IN-CH", "Chandigarh", CountryCode),
        ("IN-DH", "Dadra and Nagar Haveli and Daman and Diu", CountryCode),
        ("IN-DL", "Delhi", CountryCode),
        ("IN-JK", "Jammu and Kashmir", CountryCode),
        ("IN-LA", "Ladakh", CountryCode),
        ("IN-LD", "Lakshadweep", CountryCode),
        ("IN-PY", "Puducherry", CountryCode),
    ];

    public static IReadOnlyList<(string Code, string DisplayName, string ParentCode)> Cities { get; } =
    [
        // Andhra Pradesh
        ("IN-AP-VIZ", "Visakhapatnam", "IN-AP"),
        ("IN-AP-VJA", "Vijayawada", "IN-AP"),
        ("IN-AP-GNT", "Guntur", "IN-AP"),
        ("IN-AP-NEL", "Nellore", "IN-AP"),
        ("IN-AP-KUR", "Kurnool", "IN-AP"),
        ("IN-AP-TIR", "Tirupati", "IN-AP"),
        ("IN-AP-KAK", "Kakinada", "IN-AP"),
        ("IN-AP-RAJ", "Rajahmundry", "IN-AP"),
        ("IN-AP-ANP", "Anantapur", "IN-AP"),
        // Arunachal Pradesh
        ("IN-AR-ITN", "Itanagar", "IN-AR"),
        ("IN-AR-NAH", "Naharlagun", "IN-AR"),
        ("IN-AR-PAS", "Pasighat", "IN-AR"),
        ("IN-AR-TAW", "Tawang", "IN-AR"),
        ("IN-AR-ZIR", "Ziro", "IN-AR"),
        // Assam
        ("IN-AS-GUW", "Guwahati", "IN-AS"),
        ("IN-AS-SIL", "Silchar", "IN-AS"),
        ("IN-AS-DIB", "Dibrugarh", "IN-AS"),
        ("IN-AS-JOR", "Jorhat", "IN-AS"),
        ("IN-AS-NAG", "Nagaon", "IN-AS"),
        ("IN-AS-TEZ", "Tezpur", "IN-AS"),
        ("IN-AS-TIN", "Tinsukia", "IN-AS"),
        // Bihar
        ("IN-BR-PAT", "Patna", "IN-BR"),
        ("IN-BR-GAY", "Gaya", "IN-BR"),
        ("IN-BR-BHA", "Bhagalpur", "IN-BR"),
        ("IN-BR-MUZ", "Muzaffarpur", "IN-BR"),
        ("IN-BR-PUR", "Purnia", "IN-BR"),
        ("IN-BR-DAR", "Darbhanga", "IN-BR"),
        ("IN-BR-ARA", "Arrah", "IN-BR"),
        // Chhattisgarh
        ("IN-CG-RAI", "Raipur", "IN-CG"),
        ("IN-CG-BIL", "Bilaspur", "IN-CG"),
        ("IN-CG-KOR", "Korba", "IN-CG"),
        ("IN-CG-DUR", "Durg", "IN-CG"),
        ("IN-CG-BHI", "Bhilai", "IN-CG"),
        ("IN-CG-JAG", "Jagdalpur", "IN-CG"),
        // Goa
        ("IN-GA-PAN", "Panaji", "IN-GA"),
        ("IN-GA-MAR", "Margao", "IN-GA"),
        ("IN-GA-VAS", "Vasco da Gama", "IN-GA"),
        ("IN-GA-MAP", "Mapusa", "IN-GA"),
        ("IN-GA-PON", "Ponda", "IN-GA"),
        // Gujarat
        ("IN-GJ-AMD", "Ahmedabad", "IN-GJ"),
        ("IN-GJ-SUR", "Surat", "IN-GJ"),
        ("IN-GJ-VAD", "Vadodara", "IN-GJ"),
        ("IN-GJ-RAJ", "Rajkot", "IN-GJ"),
        ("IN-GJ-BHA", "Bhavnagar", "IN-GJ"),
        ("IN-GJ-JAM", "Jamnagar", "IN-GJ"),
        ("IN-GJ-GAN", "Gandhinagar", "IN-GJ"),
        ("IN-GJ-JUN", "Junagadh", "IN-GJ"),
        // Haryana
        ("IN-HR-GUR", "Gurugram", "IN-HR"),
        ("IN-HR-FAR", "Faridabad", "IN-HR"),
        ("IN-HR-PAN", "Panipat", "IN-HR"),
        ("IN-HR-AMB", "Ambala", "IN-HR"),
        ("IN-HR-HIS", "Hisar", "IN-HR"),
        ("IN-HR-KAR", "Karnal", "IN-HR"),
        ("IN-HR-ROH", "Rohtak", "IN-HR"),
        // Himachal Pradesh
        ("IN-HP-SHI", "Shimla", "IN-HP"),
        ("IN-HP-DHA", "Dharamshala", "IN-HP"),
        ("IN-HP-MAN", "Mandi", "IN-HP"),
        ("IN-HP-SOL", "Solan", "IN-HP"),
        ("IN-HP-KUL", "Kullu", "IN-HP"),
        ("IN-HP-HAM", "Hamirpur", "IN-HP"),
        // Jharkhand
        ("IN-JH-RAN", "Ranchi", "IN-JH"),
        ("IN-JH-JAM", "Jamshedpur", "IN-JH"),
        ("IN-JH-DHA", "Dhanbad", "IN-JH"),
        ("IN-JH-BOK", "Bokaro", "IN-JH"),
        ("IN-JH-DEO", "Deoghar", "IN-JH"),
        ("IN-JH-HAZ", "Hazaribagh", "IN-JH"),
        // Karnataka
        ("IN-KA-BLR", "Bengaluru", "IN-KA"),
        ("IN-KA-MYS", "Mysuru", "IN-KA"),
        ("IN-KA-MNG", "Mangaluru", "IN-KA"),
        ("IN-KA-HUB", "Hubballi", "IN-KA"),
        ("IN-KA-BEL", "Belagavi", "IN-KA"),
        ("IN-KA-KAL", "Kalaburagi", "IN-KA"),
        ("IN-KA-DAV", "Davanagere", "IN-KA"),
        ("IN-KA-SHI", "Shivamogga", "IN-KA"),
        // Kerala
        ("IN-KL-TVM", "Thiruvananthapuram", "IN-KL"),
        ("IN-KL-COK", "Kochi", "IN-KL"),
        ("IN-KL-KOZ", "Kozhikode", "IN-KL"),
        ("IN-KL-THR", "Thrissur", "IN-KL"),
        ("IN-KL-KOL", "Kollam", "IN-KL"),
        ("IN-KL-KAN", "Kannur", "IN-KL"),
        ("IN-KL-PAL", "Palakkad", "IN-KL"),
        // Madhya Pradesh
        ("IN-MP-BHO", "Bhopal", "IN-MP"),
        ("IN-MP-IND", "Indore", "IN-MP"),
        ("IN-MP-JAB", "Jabalpur", "IN-MP"),
        ("IN-MP-GWA", "Gwalior", "IN-MP"),
        ("IN-MP-UJJ", "Ujjain", "IN-MP"),
        ("IN-MP-SAG", "Sagar", "IN-MP"),
        ("IN-MP-RAT", "Ratlam", "IN-MP"),
        // Maharashtra
        ("IN-MH-MUM", "Mumbai", "IN-MH"),
        ("IN-MH-PUN", "Pune", "IN-MH"),
        ("IN-MH-NAG", "Nagpur", "IN-MH"),
        ("IN-MH-NAS", "Nashik", "IN-MH"),
        ("IN-MH-AUR", "Aurangabad", "IN-MH"),
        ("IN-MH-KOL", "Kolhapur", "IN-MH"),
        ("IN-MH-THA", "Thane", "IN-MH"),
        ("IN-MH-SOL", "Solapur", "IN-MH"),
        ("IN-MH-AMR", "Amravati", "IN-MH"),
        // Manipur
        ("IN-MN-IMP", "Imphal", "IN-MN"),
        ("IN-MN-THO", "Thoubal", "IN-MN"),
        ("IN-MN-BIS", "Bishnupur", "IN-MN"),
        // Meghalaya
        ("IN-ML-SHI", "Shillong", "IN-ML"),
        ("IN-ML-TUR", "Tura", "IN-ML"),
        ("IN-ML-JOW", "Jowai", "IN-ML"),
        // Mizoram
        ("IN-MZ-AIZ", "Aizawl", "IN-MZ"),
        ("IN-MZ-LUN", "Lunglei", "IN-MZ"),
        ("IN-MZ-CHA", "Champhai", "IN-MZ"),
        // Nagaland
        ("IN-NL-KOH", "Kohima", "IN-NL"),
        ("IN-NL-DIM", "Dimapur", "IN-NL"),
        ("IN-NL-MOK", "Mokokchung", "IN-NL"),
        // Odisha
        ("IN-OR-BHU", "Bhubaneswar", "IN-OR"),
        ("IN-OR-CUT", "Cuttack", "IN-OR"),
        ("IN-OR-ROU", "Rourkela", "IN-OR"),
        ("IN-OR-PUR", "Puri", "IN-OR"),
        ("IN-OR-SAM", "Sambalpur", "IN-OR"),
        ("IN-OR-BER", "Berhampur", "IN-OR"),
        // Punjab
        ("IN-PB-LUD", "Ludhiana", "IN-PB"),
        ("IN-PB-AMR", "Amritsar", "IN-PB"),
        ("IN-PB-JAL", "Jalandhar", "IN-PB"),
        ("IN-PB-PAT", "Patiala", "IN-PB"),
        ("IN-PB-BAT", "Bathinda", "IN-PB"),
        ("IN-PB-MOH", "Mohali", "IN-PB"),
        ("IN-PB-PAT2", "Pathankot", "IN-PB"),
        // Rajasthan
        ("IN-RJ-JAI", "Jaipur", "IN-RJ"),
        ("IN-RJ-JOD", "Jodhpur", "IN-RJ"),
        ("IN-RJ-UDA", "Udaipur", "IN-RJ"),
        ("IN-RJ-KOT", "Kota", "IN-RJ"),
        ("IN-RJ-AJM", "Ajmer", "IN-RJ"),
        ("IN-RJ-BIK", "Bikaner", "IN-RJ"),
        ("IN-RJ-ALW", "Alwar", "IN-RJ"),
        ("IN-RJ-BHA", "Bharatpur", "IN-RJ"),
        // Sikkim
        ("IN-SK-GAN", "Gangtok", "IN-SK"),
        ("IN-SK-NAM", "Namchi", "IN-SK"),
        ("IN-SK-GYA", "Gyalshing", "IN-SK"),
        // Tamil Nadu
        ("IN-TN-CHE", "Chennai", "IN-TN"),
        ("IN-TN-CBE", "Coimbatore", "IN-TN"),
        ("IN-TN-MDU", "Madurai", "IN-TN"),
        ("IN-TN-TRI", "Tiruchirappalli", "IN-TN"),
        ("IN-TN-SAL", "Salem", "IN-TN"),
        ("IN-TN-TIR", "Tiruppur", "IN-TN"),
        ("IN-TN-VEL", "Vellore", "IN-TN"),
        ("IN-TN-ERD", "Erode", "IN-TN"),
        ("IN-TN-TNJ", "Thanjavur", "IN-TN"),
        // Telangana
        ("IN-TG-HYD", "Hyderabad", "IN-TG"),
        ("IN-TG-WAR", "Warangal", "IN-TG"),
        ("IN-TG-NIZ", "Nizamabad", "IN-TG"),
        ("IN-TG-KAR", "Karimnagar", "IN-TG"),
        ("IN-TG-KHA", "Khammam", "IN-TG"),
        ("IN-TG-MAH", "Mahbubnagar", "IN-TG"),
        // Tripura
        ("IN-TR-AGR", "Agartala", "IN-TR"),
        ("IN-TR-UDA", "Udaipur", "IN-TR"),
        ("IN-TR-DHA", "Dharmanagar", "IN-TR"),
        // Uttar Pradesh
        ("IN-UP-LKO", "Lucknow", "IN-UP"),
        ("IN-UP-KAN", "Kanpur", "IN-UP"),
        ("IN-UP-VAR", "Varanasi", "IN-UP"),
        ("IN-UP-AGR", "Agra", "IN-UP"),
        ("IN-UP-MEE", "Meerut", "IN-UP"),
        ("IN-UP-PRY", "Prayagraj", "IN-UP"),
        ("IN-UP-GHA", "Ghaziabad", "IN-UP"),
        ("IN-UP-NOI", "Noida", "IN-UP"),
        ("IN-UP-BAR", "Bareilly", "IN-UP"),
        ("IN-UP-MOR", "Moradabad", "IN-UP"),
        // Uttarakhand
        ("IN-UK-DEH", "Dehradun", "IN-UK"),
        ("IN-UK-HAR", "Haridwar", "IN-UK"),
        ("IN-UK-ROO", "Roorkee", "IN-UK"),
        ("IN-UK-HAL", "Haldwani", "IN-UK"),
        ("IN-UK-NAI", "Nainital", "IN-UK"),
        ("IN-UK-RIS", "Rishikesh", "IN-UK"),
        // West Bengal
        ("IN-WB-KOL", "Kolkata", "IN-WB"),
        ("IN-WB-HOW", "Howrah", "IN-WB"),
        ("IN-WB-DUR", "Durgapur", "IN-WB"),
        ("IN-WB-ASA", "Asansol", "IN-WB"),
        ("IN-WB-SIL", "Siliguri", "IN-WB"),
        ("IN-WB-MAL", "Malda", "IN-WB"),
        ("IN-WB-KHA", "Kharagpur", "IN-WB"),
        // Union Territories
        ("IN-AN-PBL", "Port Blair", "IN-AN"),
        ("IN-CH-CHD", "Chandigarh", "IN-CH"),
        ("IN-DH-DAM", "Daman", "IN-DH"),
        ("IN-DH-DIU", "Diu", "IN-DH"),
        ("IN-DH-SIL", "Silvassa", "IN-DH"),
        ("IN-DL-NDL", "New Delhi", "IN-DL"),
        ("IN-DL-DEL", "Delhi", "IN-DL"),
        ("IN-DL-DWK", "Dwarka", "IN-DL"),
        ("IN-DL-ROH", "Rohini", "IN-DL"),
        ("IN-JK-SRI", "Srinagar", "IN-JK"),
        ("IN-JK-JAM", "Jammu", "IN-JK"),
        ("IN-JK-ANA", "Anantnag", "IN-JK"),
        ("IN-JK-BAR", "Baramulla", "IN-JK"),
        ("IN-LA-LEH", "Leh", "IN-LA"),
        ("IN-LA-KAR", "Kargil", "IN-LA"),
        ("IN-LD-KAV", "Kavaratti", "IN-LD"),
        ("IN-PY-PUD", "Puducherry", "IN-PY"),
        ("IN-PY-KAR", "Karaikal", "IN-PY"),
        ("IN-PY-YAN", "Yanam", "IN-PY"),
    ];
}
